---
abstract: 'Tapper - Testplan support with TaskJuggler interoperability'
author:
  - 'AMD OSRC Tapper Team <tapper@amd64.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::Differences: 0
  Test::MockModule: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Tapper-Testplan
no_index:
  directory:
    - inc
    - t
requires:
  CHI: 0
  DateTime: 0
  DateTime::Format::DateParse: 0
  DateTime::Format::Natural: 0.91
  DateTime::Format::Strptime: 0
  Email::Sender::Simple: 0
  Email::Sender::Transport::SMTP: 0
  Email::Simple: 0
  File::ShareDir: 0
  File::Slurp: 0
  Moose: 0
  Tapper::Cmd: 3.000004
  Tapper::Config: 3.000002
  Tapper::Model: 3.000002
  Template: 0
  Text::CSV::Slurp: 0
  WWW::Mechanize: 0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/ReportBug.html?Queue=Tapper-Testplan
  license: http://dev.perl.org/licenses/
  repository: git://github.com/amd/Tapper-Testplan.git
version: 3.000005
